### ISSUE TITLE
Highlight changes

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#10]
Show (Changed) or color in a different color for the changed entries in iqamas/Jumaas.

**Comment by hammady** [comment]
Full schema with change booleans:

```json
{
    "max_jumaas": 5,
    "masjids": {
        "MNNexus": {
            "iqamas": {
                "fajr": {
                    "time": "7:20 am"
                },
                "zuhr": {
                    "time": "1:55 pm",
                    "changed": true
                },
                "asr": {
                    "time": "5:15 pm"
                },
                "maghrib": {
                    "time": "6:50 pm"
                },
                "isha": {
                    "time": "8:15 pm"
                }
            },
            "jumas": [
                "1:15 pm - Muslim Neighbour Nexus, 3520 Odyssey Dr, Mississauga, ON L5M 0Y9",
                "2:15 pm - Muslim Neighbour Nexus, 3520 Odyssey Dr, Mississauga, ON L5M 0Y9",
                "3:00 pm - Muslim Neighbour Nexus, 3520 Odyssey Dr, Mississauga, ON L5M 0Y9",
                "1:30 pm - Churchill Meadows Community Centre 5320 Ninth Line, Mississauga, ON L5M 0R5",
                "2:15 pm - Churchill Meadows Community Centre 5320 Ninth Line, Mississauga, ON L5M 0R5"
            ],
            "jumas_changed": true
        },
        "Shalimar": {
            "iqamas": {
                "fajr": {
                    "time": "6:45 am",
                    "changed": true
                },
                "zuhr": {
                    "time": "1:50 pm"
                },
                "asr": {
                    "time": "5:15 pm"
                },
                "maghrib": {
                    "time": "7:10 pm"
                },
                "isha": {
                    "time": "08:45 pm"
                }
            },
            "jumas": [
                "12:35 pm - Shalimar. Walk-in. Come 5 mins early.",
                "1:35 pm - Shalimar. Walk-in. Come 5 mins early."
            ]
        }
    }
}
```

**Comment by fayez-nazzal** [comment]
@hammady, I think some badges would do it. Just have one question: unlike emails, changed here seems misleading because it's not relative to anything. How much time needs to pass for a prayer time to stop being "changed"? We have times in the year when it remains almost fixed for a long time. Or is it "changed" for a prayer time relative to the other prayer times?

**Comment by hammady** [comment]
The changed flag per prayer means changed since yesterday. It will be set to true when the scraper finds a new value. The next day it will be the same so the flag will be removed. 
It could be badge, background color, text...
It can also be for the jumaa prayers.

**Comment by hammady** [comment]
@fayez-nazzal you know what, you are right. The assumption that it was changed since yesterday is coupled with the scraping schedule. It is also limiting the scraping to once daily so that the semantics do not change while I wanted to increase the frequency to 2 or 4 times a day. It is also confusing to the users when they don't visit the site daily.

Here is my plan: forget about the `changed` flag. I will keep it just for the email notifications because it serves the purpose very well. I will introduce a new field for each prayer: `changed_since` which will denote the relative time the change is measure on. Basically, if this field is blank, then no change is detected for any reason (could be the first time scraping ever, or first scraping after deploying this feature). If there is a timestamp there, it means the current value has changed since this timestamp. When the scraper fetches new data, it copies this field as is from the old values and only overrides it when a new change is detected.

In the web frontend, we will measure the difference between this timestamp and the current time. If it is bigger than a value that we agree on (let's say 24 hours), then the field is highlighted with a tooltip or footer information showing the changed since timestamp. We can even have a gradient shade or 2 colours. If changed within 1 day, we show red, if 1-3 days we show yellow, > 3 days no shade at all. I also think this field should just be date not date-time.
What do you think?

**Comment by fayez-nazzal** [comment]
@hammady That's much more useful and makes sense. There are many possibilities for how we could indicate that new update visually. I think color coding looks good, but we need to indicate what those codes mean in the bottom-right of the table.

**Comment by hammady** [comment]
Great! Please share a design for the colour coding and we can discuss on it. I need some time to implement this change, will try to dedicate some time tonight.

**Comment by hammady** [comment]
Sorry got stuck in #56, will work on this tomorrow inshaAllah!

**Comment by hammady** [comment]
@fayez-nazzal Backend change done.
There are 3 cases for any prayer (jumas are exlcuded):

1. There is no information about when current value was changed:
```json
            "iqamas": {
                "fajr": {
                    "time": "6:50 AM"
                },
            }
```

2. Current value was changed on this date, but from an old scrape:
```json
            "iqamas": {
                "fajr": {
                    "time": "6:50 AM",
                    "changed_on": "2023-10-25"
                },
             }
```

3. Current value was changed on this date from the newest scrape:
```json
            "iqamas": {
                "fajr": {
                    "time": "6:50 AM",
                    "changed": true,
                    "changed_on": "2023-10-25"
                },
            }
```

We don't really care about the difference between 2 and 3. The `changed` flag is used in email notifications only.

It will be perfect if we can display the relative time for this new field but with a day granularity, e.g. today, yesterday, Tuesday, last week, last month, ... We don't want to show 3 seconds ago, 20 minutes ago, 4 hours ago, ...

**Comment by fayez-nazzal** [comment]
> @fayez-nazzal Backend change done. There are 3 cases for any prayer (jumas are exlcuded):
> 
> 1. There is no information about when current value was changed:
> 
> ```json
>             "iqamas": {
>                 "fajr": {
>                     "time": "6:50 AM"
>                 },
>             }
> ```
> 
> 2. Current value was changed on this date, but from an old scrape:
> 
> ```json
>             "iqamas": {
>                 "fajr": {
>                     "time": "6:50 AM",
>                     "changed_on": "2023-10-25"
>                 },
>              }
> ```
> 
> 3. Current value was changed on this date from the newest scrape:
> 
> ```json
>             "iqamas": {
>                 "fajr": {
>                     "time": "6:50 AM",
>                     "changed": true,
>                     "changed_on": "2023-10-25"
>                 },
>             }
> ```
> 
> We don't really care about the difference between 2 and 3. The `changed` flag is used in email notifications only.
> 
> It will be perfect if we can display the relative time for this new field but with a day granularity, e.g. today, yesterday, Tuesday, last week, last month, ... We don't want to show 3 seconds ago, 20 minutes ago, 4 hours ago, ...

This looks good! Thanks!

**Comment by hammady** [comment]
Maybe we just show the changed value in red if today. Otherwise, normal font colour. If older than a week, do not show. This enhances the experience because typically the value becomes useless if it is too far away.

**Comment by fayez-nazzal** [comment]
@hammady What about highlighting changes for jumas? #63

**Comment by hammady** [comment]
@fayez-nazzal
I am rethinking the value for the "jumas_changed" field. Usually timings do not change, only khateebs if mentioned, and it is done late Thursday every week. Let's not add it now.
