### ISSUE TITLE
Search immediately on type

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#28]
With all the data loaded locally, it should be lightning fast to search immediately on every change in the search box. Currently the user has to press Enter.

**Comment by hammady** [comment]
Search is now broken after introducing the new layout.

**Comment by hammady** [comment]
What happens if a user searches while in the prayers layout? I think we should search in prayer names instead, or we disable search for this layout.

**Comment by hammady** [comment]
@fayez-nazzal this is now broken too.

**Comment by fayez-nazzal** [comment]
Ops, I will check it
