### ISSUE TITLE
Side-bar remembers previous selections

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#29]
When I click on subscribe it auto-selects the current masjid which is ok, but when I close the sidebar without clicking on subscribe, it will remember that masjid and it will be auto-checked when I select another masjid. I expect the side-bar to be reset the checkboxes when I close it.

**Comment by fayez-nazzal** [comment]
@hammady I'm making PRs for fixes and mini enhancements before doing anything new, will include this.
