### ISSUE TITLE
Many of the texts are Tile Cased

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#33]
Like Pm Am, ... even jumuas. I think this is unnecessary. If we want to title case the prayer names, that would strictly apply to this column only in all tables, or have a lookup.

**Comment by fayez-nazzal** [comment]
@hammady Is it a simple CSS change (upper,lower,capitalize) or requires runtime processing through the text?

**Comment by hammady** [comment]
I don't know how it gets transformed. The data files contain normal case "am", but I see it on the generated html "Am". I thought you are manipulating it?

**Comment by fayez-nazzal** [comment]
@hammady Will include this too

**Comment by hammady** [comment]
Let's put it back in the prayer names column please.

**Comment by fayez-nazzal** [comment]
@hammady We can add the class name on one column

**Comment by hammady** [comment]
Yes, please do.
