### ISSUE TITLE
Add more metadata to masjids

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#34]
Currently the only metadata is the masjid name, and because it is used as the topic name, it has some restrictions (cannot have spaces). We can add more metadata like display name, URL, and address.

**Comment by hammady** [comment]
Related to this: store them when scraped in a specific order (alphabetically for e.g.). Theoretically there is no order in JSON objects, but practically they are displayed in the same order they are read from the file.

**Comment by hammady** [comment]
@fayez-nazzal new schema including metadata:

```json
        "WestEndIslamicCenter": {                                                                                                                       
            "display_name": "West End Islamic Center",                                                                                                  
            "website": "https://weicenter.ca/",                                                                                                         
            "address": "12,13-4161 Sladeview Crescent, Mississauga, ON L5L 5R3",                                                                        
            "iqamas": {},
            ...
    ...
```

**Comment by hammady** [comment]
We can show the masjid display name in the header instead of the code and make it linkable with the website. We can also show the display name in the subscribe sidebar. The address can be shown in a smaller font below the masjid name.

**Comment by fayez-nazzal** [comment]
@hammady Insha'allah will do it tomorrow's morning
