### ISSUE TITLE
Assign domain aliases to the CloudFront distros

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#42]

**Comment by hammady** [comment]
CloudFormation updated to add aliases and certificates to CloudFront distributions here: 5667a3ee1765dc8749c40c3e75e1d2d9b7652507.
Things done manually:
- Create ACM certificate on AWS console and corresponding Route 53 CNAMEs.
- Create Alias records on Route 53 after deploying the updated CloudFormation in the generator service.

@fayez-nazzal please check here: https://wwpray.net/

**Comment by fayez-nazzal** [comment]
> https://wwpray.net/

@hammady Amazing!!!
