### ISSUE TITLE
Handle last_updated timestamp for each masjid separatley

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#47]
After implementing #46, some masjids will fail to update, and the global last_updated flag will be misleading. We will still keep it as it denotes the last update for all masjids, and it is used in triggering the generator function. However, we should add to the json schema `last_updated` for each masjid. If a masjid fails to update, the generated data file should copy values from the previous scraping trigger. If it succeeds, new values are generated with a fresh last_updated timestamp.

**Comment by fayez-nazzal** [comment]
@hammady Does this impact implementing #6 ?

**Comment by hammady** [comment]
@fayez-nazzal yes, I also commented there :)

**Comment by hammady** [comment]
@fayez-nazzal last_updated.txt is now deprecated, and here is the new schema:

```json
{
    "max_jumaas": 2,
    "masjids": {
        "ICCO": {
            "iqamas": {
                "fajr": {
                    "time": "6:50 am",
                    "changed": true
                },
                "zuhr": {
                    "time": "2:00 pm"
                },
                "asr": {
                    "time": "4:45 pm"
                },
                "maghrib": {
                    "time": "6:35 pm"
                },
                "isha": {
                    "time": "8:00 pm"
                }
            },
            "jumas": [
                "12:35 P.M. by Jawad Salman (English)",
                "1:30 P.M. by Wael Hamadeh (English)",
                "2:45 P.M. by Sheikh Samir Khalil (Arabic)"
            ],
            "jumas_changed": true,
            "last_updated": "2023-10-21T03:41:47.555916"
        }
    }
}
```
