### ISSUE TITLE
Show last updated timestamp in relative time format

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#6]

**Comment by fayez-nazzal** [comment]
@hammady 

I think `dayjs` is a solid option and the most minimal. We can go more advanced using `luxon`, but I don't see any need now. 

There is also an option to use JavaScript's temporal API polyfill, then when browsers' JavaScript officially supports it, we can remove it without any more changes.

All mentioned options are superior to `moment`, especially for dev experience and cleanness.

Let me know your thoughts!

**Comment by hammady** [comment]
I trust your judgement for the best approach.

**Comment by hammady** [comment]
@fayez-nazzal The scope will change soon to show last_updated timestamp for each masjid individually.
See #47.

**Comment by fayez-nazzal** [comment]
@hammady I just read this comment, alright!

**Comment by hammady** [comment]
New schema:
```json
{
    "max_jumaas": 2,
    "masjids": {
        "ICCO": {
            "iqamas": {
                "fajr": {
                    "time": "6:50 am",
                    "changed": true
                },
                "zuhr": {
                    "time": "2:00 pm"
                },
                "asr": {
                    "time": "4:45 pm"
                },
                "maghrib": {
                    "time": "6:35 pm"
                },
                "isha": {
                    "time": "8:00 pm"
                }
            },
            "jumas": [
                "12:35 P.M. by Jawad Salman (English)",
                "1:30 P.M. by Wael Hamadeh (English)",
                "2:45 P.M. by Sheikh Samir Khalil (Arabic)"
            ],
            "jumas_changed": true,
            "last_updated": "2023-10-21T03:41:47.555916"
        }
    }
}
```

**Comment by hammady** [comment]
The `last_updated` timestamp shows the UTC time in iso format. Without JS, it would show as is. With JS, it needs to be shown relatively.

**Comment by hammady** [comment]
@fayez-nazzal Probably this is not the latest code but it shows in 13 minutes while it should be 4 hours ago. 
Is there a timezone issue?
My time zone is -4.
![image](https://github.com/hammady/wwpray/assets/855847/99d58e45-7e54-441d-9a05-00aff48536a0)

**Comment by hammady** [comment]
I think there is a timezone issue. This timestamp is 3am EST or 7am UTC. It is now showing 10 minutes ago and the time now EST is 7:10. It handles the value as being in current timezone while it should be parsed as UTC. 
![image](https://github.com/hammady/wwpray/assets/855847/dfe79753-edee-4cd1-94da-5b371b7fd893)

**Comment by fayez-nazzal** [comment]
@hammady Ops..my fault, I will fix this.
