### ISSUE TITLE
Changed on subtracts one extra day

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#68]
Take a look at the current values for DarFoundation:
```json
                "maghrib": {
                    "time": "6:22 PM",
                    "changed": true,
                    "changed_on": "2023-10-28"
                },
                "isha": {
                    "time": "7:45 PM",
                    "changed": true,
                    "changed_on": "2023-10-28"
                }
```
Take a look now on wwpray.net:

<img width="834" alt="image" src="https://github.com/hammady/wwpray/assets/855847/6d71d029-f45b-4cf3-a893-938a7e943cdf">

These should show today in the interface.

Now is 28-10 10:40am EST.

**Comment by fayez-nazzal** [comment]
I see this happens all the time when using dayjs and it turned out I'm not alone! 

A quick question that may help, when we parse something as UTC, should we localize it again?

**Comment by hammady** [comment]
I don't know the answer, but it could be related to timezones.

**Comment by hammady** [comment]
@fayez-nazzal could be related. Today is Nov 4 and it was showing me 28/10/2023 for one of the masjids. I expect older than last week to be hidden.

![image](https://github.com/hammady/wwpray/assets/855847/62a0a54c-71d1-4371-8cfe-3d4511c01f2b)
