### ISSUE TITLE
Refreshing the site on client-side navigation errors out

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#73]
If you navigate to a different layout e.g. Jumas, the browser navigation is replaced by `/jumas`. If you try to refresh the page, you get an error because CloudFront doesn't know this location.
Is there a way to use anchors instead of paths, then we do deep linking when the page loads with an anchor?

**Comment by fayez-nazzal** [comment]
@hammady 

We need the HTML files for those routes, currently, we only have `index.html`

The reason why we have routes is Zero-JS support. CSR needs JS. but we have 2 nice features that could be helpful to us:
- We can set a `fallback` page to `index.html` when an unknown route is visited. I could add a PR for that if needed.
- If we are worried about the size of the output, we can use `gzip` or `brotli` compression (or both). This will be a significant size reduction. I tried it for `wwpray` and got about 86% reduction for gzip and 91% reduced size for brotli. I believe python simple HTTP server supports both to be served.

**Comment by fayez-nazzal** [comment]
@hammady EDIT: I mean CloudFront, that was a mindless sentence lol

**Comment by hammady** [comment]
Yeah, the fallback needs to be done on CloudFront. Do we just generate identical files to `index.html` with the route names?
For compression, this is already handled by CF. Inspect any 200 response and you will notice the content-encoding: gzip header returned.

**Comment by fayez-nazzal** [comment]
@hammady 

Yes the fallback is better to be done in CloudFront because otherwise it will require JavaScript, those options are specified by [Svelte Static Adapter](https://kit.svelte.dev/docs/adapter-static)

The compression will generate `html.br` files. Can we use brotli directly and ignore the rest? It's supported by every browser (Except IE and Opera Mini, those are not browsers)

![image](https://github.com/hammady/wwpray/assets/49946791/cf23b358-f199-49dc-8340-ea16a2ecc52a)

![image](https://github.com/hammady/wwpray/assets/49946791/d8aea65e-5735-4c7a-9d6d-886a3503cee3)

**Comment by hammady** [comment]
Will test with the new merged PR. Let's disable compression on the app level as it is not used. It is the CDN concern.

**Comment by fayez-nazzal** [comment]
@hammady The compression is disabled, seems that now the issue is "Access Denied", seems an S3 issue?

**Comment by hammady** [comment]
@fayez-nazzal the problem still happens because we now upload the other 2 layouts as files. What actually happens on CloudFront is that it interprets the paths as directory names then it tries to list their `index.html` which is not there.
We can solve this in 3 ways:
1. Modify the navigation such that switching the tabs replaces the address with a path ending with `.html`.
2. Creating directories on s3, then uploading the html files for the other layouts under those with a new name `index.html`.
3. Stripping out the `.html` suffix when uploading. I just tried this and it works! I will create a PR.
