### ISSUE TITLE
Search is broken on mobile

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#77]
It works well on desktop. On trying Safari and Edge for iOS it doesn't work. Moreover, the layouts are not clickable anymore.

**Comment by hammady** [comment]
I suggest that we also hide the intro text when search is active to bring results closer to the top without the need to scroll down.

**Comment by fayez-nazzal** [comment]
@hammady I think it's not only a search problem, the app on mobile doesn't work well at all, I will do that this weekend insha'allah
