### ISSUE TITLE
Highlight the next prayer in all masjids

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#9]
This basically answers the main question: Where And When to pray! We can even put this info above all tables.

**Comment by hammady** [comment]
Related to #5, if the grouping is by masjid we highlight the next prayer in all tables. If the grouping is by prayer, we show the next prayer as the first group, followed by others in sequence. For example, if the next prayer is Asr, the order will be:
Asr - Maghrib - Isha - Fajr - Zuhr.

**Comment by fayez-nazzal** [comment]
@hammady We will have the compact layout as a separate component, possible to handle each in a different way.

**Comment by fayez-nazzal** [comment]
This will be closed after adding highlights for jumaas, I will do #63 first)
